### ISSUE TITLE
Score cut off at top/bottom ?

### ISSUE THREAD

**Issue by konstantinblaesi** [keijokapp/score-util#10]
Working [with this score](https://musescore.com/user/1630246/scores/13076131)

![vlcsnap-2024-03-22-23h50m25s150](https://github.com/keijokapp/score-util/assets/5871169/0bb01f6d-d9ec-4e2b-b6a8-69ca4a512e05)

Or with different scaling

![vlcsnap-2024-03-22-23h51m02s802](https://github.com/keijokapp/score-util/assets/5871169/3d222221-557e-4217-a658-83b504aad046)

Do you know why this is happening ?

**Comment by keijokapp** [comment]
Handling large systems is a known limitation as outlined in the README:
> The video width is harcoded to page width and aspect ration is hardcoded to 16:9. Higher systems might not fit into that rectangle and are clipped.

I guess technically it would be easy to implement just zooming out if the system's height exceeds the boundaries. But I'm not sure if a naive per-system zoom would be the best strategy because varying system heights would also result in varying zoom levels which can be annoying. Though it's better than nothing so probably worth adding.
